function analyse_male_behaviour(genotypelists, genotypes, olddataformat)
run_distance_travelled(600)
run_mean_dist_to_other()
run_mean_velocity(900)
find_videos_male_behaviour(genotypelists, genotypes, olddataformat)