function analyse_male_behaviour(genotypelists, genotypes, olddataformat)
run_distance_travelled(600)
run_mean_dist_to_other()
run_mean_velocity(900)
run_time_to_leg_touch(2)
run_time_to_movement(4)
run_time_to_dist(2)
find_videos_male_behaviour(genotypelists, genotypes, olddataformat)