function pausing_smaller_chamber()
%%%PAUSING_SMALLER_CHAMBER()
%%%Annika Rings, 2021
%%%function determines fraction of frames showing
%%%pausing based on Voshall et al criteria for pausing in a smaller chamber
%%%the function uses the fraction_frames(varargin) function

run_fraction('pausing',1,'cutoff',2, 'below',true,...
'wingextonly',false,'additional',14,...
'additional_cutoff',13,'additional_below',true,...
'additional2',10,...
'additional2_cutoff',5,'additional2_below',true)