function pausing()
run_fraction('pausing',1,'cutoff',4, 'below',true,...
'wingextonly',false,'additional',14,...
'additional_cutoff',15,'additional_below',true,...
'additional2',10,...
'additional2_cutoff',10,'additional2_below',true)